version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/testplanit"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@zenstackhq/server"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@zenstackhq/tanstack-query"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@eslint/js"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-resizable-panels"
        update-types: ["version-update:semver-major"]
    groups:
      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "@types/node"
      minor-and-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "@types/node"
      minor-and-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "@types/node"
      minor-and-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
