/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, ApiToken } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateApiToken(options?: Omit<(UseMutationOptions<(ApiToken | undefined), DefaultError, Prisma.ApiTokenCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ApiTokenCreateArgs, DefaultError, ApiToken, true>('ApiToken', 'POST', `${endpoint}/apiToken/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ApiTokenCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ApiTokenCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ApiToken, Prisma.ApiTokenGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ApiTokenCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ApiToken, Prisma.ApiTokenGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyApiToken(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ApiTokenCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ApiTokenCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ApiToken', 'POST', `${endpoint}/apiToken/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ApiTokenCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ApiTokenCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ApiTokenCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyApiToken<TArgs extends Prisma.ApiTokenFindManyArgs, TQueryFnData = Array<Prisma.ApiTokenGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ApiTokenFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/findMany`, args, options, fetch);
}

export function useInfiniteFindManyApiToken<TArgs extends Prisma.ApiTokenFindManyArgs, TQueryFnData = Array<Prisma.ApiTokenGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ApiTokenFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/findMany`, args, options, fetch);
}

export function useSuspenseFindManyApiToken<TArgs extends Prisma.ApiTokenFindManyArgs, TQueryFnData = Array<Prisma.ApiTokenGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ApiTokenFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyApiToken<TArgs extends Prisma.ApiTokenFindManyArgs, TQueryFnData = Array<Prisma.ApiTokenGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ApiTokenFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/findMany`, args, options, fetch);
}

export function useFindUniqueApiToken<TArgs extends Prisma.ApiTokenFindUniqueArgs, TQueryFnData = Prisma.ApiTokenGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ApiTokenFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueApiToken<TArgs extends Prisma.ApiTokenFindUniqueArgs, TQueryFnData = Prisma.ApiTokenGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ApiTokenFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/findUnique`, args, options, fetch);
}

export function useFindFirstApiToken<TArgs extends Prisma.ApiTokenFindFirstArgs, TQueryFnData = Prisma.ApiTokenGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ApiTokenFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstApiToken<TArgs extends Prisma.ApiTokenFindFirstArgs, TQueryFnData = Prisma.ApiTokenGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ApiTokenFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/findFirst`, args, options, fetch);
}

export function useUpdateApiToken(options?: Omit<(UseMutationOptions<(ApiToken | undefined), DefaultError, Prisma.ApiTokenUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ApiTokenUpdateArgs, DefaultError, ApiToken, true>('ApiToken', 'PUT', `${endpoint}/apiToken/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ApiTokenUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ApiTokenUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ApiToken, Prisma.ApiTokenGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ApiTokenUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ApiToken, Prisma.ApiTokenGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyApiToken(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ApiTokenUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ApiTokenUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ApiToken', 'PUT', `${endpoint}/apiToken/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ApiTokenUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ApiTokenUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ApiTokenUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertApiToken(options?: Omit<(UseMutationOptions<(ApiToken | undefined), DefaultError, Prisma.ApiTokenUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ApiTokenUpsertArgs, DefaultError, ApiToken, true>('ApiToken', 'POST', `${endpoint}/apiToken/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ApiTokenUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ApiTokenUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ApiToken, Prisma.ApiTokenGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ApiTokenUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ApiToken, Prisma.ApiTokenGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteApiToken(options?: Omit<(UseMutationOptions<(ApiToken | undefined), DefaultError, Prisma.ApiTokenDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ApiTokenDeleteArgs, DefaultError, ApiToken, true>('ApiToken', 'DELETE', `${endpoint}/apiToken/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ApiTokenDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ApiTokenDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ApiToken, Prisma.ApiTokenGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ApiTokenDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ApiToken, Prisma.ApiTokenGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyApiToken(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ApiTokenDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ApiTokenDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ApiToken', 'DELETE', `${endpoint}/apiToken/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ApiTokenDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ApiTokenDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ApiTokenDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateApiToken<TArgs extends Prisma.ApiTokenAggregateArgs, TQueryFnData = Prisma.GetApiTokenAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ApiTokenAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateApiToken<TArgs extends Prisma.ApiTokenAggregateArgs, TQueryFnData = Prisma.GetApiTokenAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ApiTokenAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/aggregate`, args, options, fetch);
}

export function useGroupByApiToken<TArgs extends Prisma.ApiTokenGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ApiTokenGroupByArgs['orderBy'] } : { orderBy?: Prisma.ApiTokenGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ApiTokenGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ApiTokenGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ApiTokenGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ApiTokenGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ApiTokenGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByApiToken<TArgs extends Prisma.ApiTokenGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ApiTokenGroupByArgs['orderBy'] } : { orderBy?: Prisma.ApiTokenGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ApiTokenGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ApiTokenGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ApiTokenGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ApiTokenGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ApiTokenGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/groupBy`, args, options, fetch);
}

export function useCountApiToken<TArgs extends Prisma.ApiTokenCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ApiTokenCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ApiTokenCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/count`, args, options, fetch);
}

export function useSuspenseCountApiToken<TArgs extends Prisma.ApiTokenCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ApiTokenCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ApiTokenCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ApiToken', `${endpoint}/apiToken/count`, args, options, fetch);
}

export function useCheckApiToken<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; name?: string; token?: string; tokenPrefix?: string; userId?: string; scopes?: string; lastUsedIp?: string; isActive?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ApiToken', `${endpoint}/apiToken/check`, args, options, fetch);
}
