/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, ColorFamily } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateColorFamily(options?: Omit<(UseMutationOptions<(ColorFamily | undefined), DefaultError, Prisma.ColorFamilyCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ColorFamilyCreateArgs, DefaultError, ColorFamily, true>('ColorFamily', 'POST', `${endpoint}/colorFamily/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ColorFamilyCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ColorFamilyCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ColorFamily, Prisma.ColorFamilyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ColorFamilyCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ColorFamily, Prisma.ColorFamilyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyColorFamily(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ColorFamilyCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ColorFamilyCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ColorFamily', 'POST', `${endpoint}/colorFamily/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ColorFamilyCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ColorFamilyCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ColorFamilyCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyColorFamily<TArgs extends Prisma.ColorFamilyFindManyArgs, TQueryFnData = Array<Prisma.ColorFamilyGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/findMany`, args, options, fetch);
}

export function useInfiniteFindManyColorFamily<TArgs extends Prisma.ColorFamilyFindManyArgs, TQueryFnData = Array<Prisma.ColorFamilyGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/findMany`, args, options, fetch);
}

export function useSuspenseFindManyColorFamily<TArgs extends Prisma.ColorFamilyFindManyArgs, TQueryFnData = Array<Prisma.ColorFamilyGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyColorFamily<TArgs extends Prisma.ColorFamilyFindManyArgs, TQueryFnData = Array<Prisma.ColorFamilyGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/findMany`, args, options, fetch);
}

export function useFindUniqueColorFamily<TArgs extends Prisma.ColorFamilyFindUniqueArgs, TQueryFnData = Prisma.ColorFamilyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueColorFamily<TArgs extends Prisma.ColorFamilyFindUniqueArgs, TQueryFnData = Prisma.ColorFamilyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/findUnique`, args, options, fetch);
}

export function useFindFirstColorFamily<TArgs extends Prisma.ColorFamilyFindFirstArgs, TQueryFnData = Prisma.ColorFamilyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstColorFamily<TArgs extends Prisma.ColorFamilyFindFirstArgs, TQueryFnData = Prisma.ColorFamilyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/findFirst`, args, options, fetch);
}

export function useUpdateColorFamily(options?: Omit<(UseMutationOptions<(ColorFamily | undefined), DefaultError, Prisma.ColorFamilyUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ColorFamilyUpdateArgs, DefaultError, ColorFamily, true>('ColorFamily', 'PUT', `${endpoint}/colorFamily/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ColorFamilyUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ColorFamilyUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ColorFamily, Prisma.ColorFamilyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ColorFamilyUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ColorFamily, Prisma.ColorFamilyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyColorFamily(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ColorFamilyUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ColorFamilyUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ColorFamily', 'PUT', `${endpoint}/colorFamily/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ColorFamilyUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ColorFamilyUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ColorFamilyUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertColorFamily(options?: Omit<(UseMutationOptions<(ColorFamily | undefined), DefaultError, Prisma.ColorFamilyUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ColorFamilyUpsertArgs, DefaultError, ColorFamily, true>('ColorFamily', 'POST', `${endpoint}/colorFamily/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ColorFamilyUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ColorFamilyUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ColorFamily, Prisma.ColorFamilyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ColorFamilyUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ColorFamily, Prisma.ColorFamilyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteColorFamily(options?: Omit<(UseMutationOptions<(ColorFamily | undefined), DefaultError, Prisma.ColorFamilyDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ColorFamilyDeleteArgs, DefaultError, ColorFamily, true>('ColorFamily', 'DELETE', `${endpoint}/colorFamily/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ColorFamilyDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ColorFamilyDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ColorFamily, Prisma.ColorFamilyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ColorFamilyDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ColorFamily, Prisma.ColorFamilyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyColorFamily(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ColorFamilyDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ColorFamilyDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ColorFamily', 'DELETE', `${endpoint}/colorFamily/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ColorFamilyDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ColorFamilyDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ColorFamilyDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateColorFamily<TArgs extends Prisma.ColorFamilyAggregateArgs, TQueryFnData = Prisma.GetColorFamilyAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateColorFamily<TArgs extends Prisma.ColorFamilyAggregateArgs, TQueryFnData = Prisma.GetColorFamilyAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/aggregate`, args, options, fetch);
}

export function useGroupByColorFamily<TArgs extends Prisma.ColorFamilyGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ColorFamilyGroupByArgs['orderBy'] } : { orderBy?: Prisma.ColorFamilyGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ColorFamilyGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ColorFamilyGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ColorFamilyGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ColorFamilyGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ColorFamilyGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByColorFamily<TArgs extends Prisma.ColorFamilyGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ColorFamilyGroupByArgs['orderBy'] } : { orderBy?: Prisma.ColorFamilyGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ColorFamilyGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ColorFamilyGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ColorFamilyGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ColorFamilyGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ColorFamilyGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/groupBy`, args, options, fetch);
}

export function useCountColorFamily<TArgs extends Prisma.ColorFamilyCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ColorFamilyCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/count`, args, options, fetch);
}

export function useSuspenseCountColorFamily<TArgs extends Prisma.ColorFamilyCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ColorFamilyCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ColorFamilyCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ColorFamily', `${endpoint}/colorFamily/count`, args, options, fetch);
}

export function useCheckColorFamily<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; name?: string; order?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ColorFamily', `${endpoint}/colorFamily/check`, args, options, fetch);
}
