/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, Configurations } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateConfigurations(options?: Omit<(UseMutationOptions<(Configurations | undefined), DefaultError, Prisma.ConfigurationsCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigurationsCreateArgs, DefaultError, Configurations, true>('Configurations', 'POST', `${endpoint}/configurations/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigurationsCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigurationsCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, Configurations, Prisma.ConfigurationsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigurationsCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Configurations, Prisma.ConfigurationsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyConfigurations(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ConfigurationsCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigurationsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Configurations', 'POST', `${endpoint}/configurations/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigurationsCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigurationsCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ConfigurationsCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyConfigurations<TArgs extends Prisma.ConfigurationsFindManyArgs, TQueryFnData = Array<Prisma.ConfigurationsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/findMany`, args, options, fetch);
}

export function useInfiniteFindManyConfigurations<TArgs extends Prisma.ConfigurationsFindManyArgs, TQueryFnData = Array<Prisma.ConfigurationsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/findMany`, args, options, fetch);
}

export function useSuspenseFindManyConfigurations<TArgs extends Prisma.ConfigurationsFindManyArgs, TQueryFnData = Array<Prisma.ConfigurationsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyConfigurations<TArgs extends Prisma.ConfigurationsFindManyArgs, TQueryFnData = Array<Prisma.ConfigurationsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/findMany`, args, options, fetch);
}

export function useFindUniqueConfigurations<TArgs extends Prisma.ConfigurationsFindUniqueArgs, TQueryFnData = Prisma.ConfigurationsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueConfigurations<TArgs extends Prisma.ConfigurationsFindUniqueArgs, TQueryFnData = Prisma.ConfigurationsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/findUnique`, args, options, fetch);
}

export function useFindFirstConfigurations<TArgs extends Prisma.ConfigurationsFindFirstArgs, TQueryFnData = Prisma.ConfigurationsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstConfigurations<TArgs extends Prisma.ConfigurationsFindFirstArgs, TQueryFnData = Prisma.ConfigurationsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/findFirst`, args, options, fetch);
}

export function useUpdateConfigurations(options?: Omit<(UseMutationOptions<(Configurations | undefined), DefaultError, Prisma.ConfigurationsUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigurationsUpdateArgs, DefaultError, Configurations, true>('Configurations', 'PUT', `${endpoint}/configurations/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigurationsUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigurationsUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, Configurations, Prisma.ConfigurationsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigurationsUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Configurations, Prisma.ConfigurationsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyConfigurations(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ConfigurationsUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigurationsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Configurations', 'PUT', `${endpoint}/configurations/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigurationsUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigurationsUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ConfigurationsUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertConfigurations(options?: Omit<(UseMutationOptions<(Configurations | undefined), DefaultError, Prisma.ConfigurationsUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigurationsUpsertArgs, DefaultError, Configurations, true>('Configurations', 'POST', `${endpoint}/configurations/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigurationsUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigurationsUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, Configurations, Prisma.ConfigurationsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigurationsUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Configurations, Prisma.ConfigurationsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteConfigurations(options?: Omit<(UseMutationOptions<(Configurations | undefined), DefaultError, Prisma.ConfigurationsDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigurationsDeleteArgs, DefaultError, Configurations, true>('Configurations', 'DELETE', `${endpoint}/configurations/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigurationsDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigurationsDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, Configurations, Prisma.ConfigurationsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigurationsDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Configurations, Prisma.ConfigurationsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyConfigurations(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ConfigurationsDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigurationsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Configurations', 'DELETE', `${endpoint}/configurations/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigurationsDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigurationsDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ConfigurationsDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateConfigurations<TArgs extends Prisma.ConfigurationsAggregateArgs, TQueryFnData = Prisma.GetConfigurationsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateConfigurations<TArgs extends Prisma.ConfigurationsAggregateArgs, TQueryFnData = Prisma.GetConfigurationsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/aggregate`, args, options, fetch);
}

export function useGroupByConfigurations<TArgs extends Prisma.ConfigurationsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ConfigurationsGroupByArgs['orderBy'] } : { orderBy?: Prisma.ConfigurationsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ConfigurationsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ConfigurationsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigurationsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigurationsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ConfigurationsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByConfigurations<TArgs extends Prisma.ConfigurationsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ConfigurationsGroupByArgs['orderBy'] } : { orderBy?: Prisma.ConfigurationsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ConfigurationsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ConfigurationsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigurationsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigurationsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ConfigurationsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/groupBy`, args, options, fetch);
}

export function useCountConfigurations<TArgs extends Prisma.ConfigurationsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ConfigurationsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/count`, args, options, fetch);
}

export function useSuspenseCountConfigurations<TArgs extends Prisma.ConfigurationsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ConfigurationsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigurationsCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Configurations', `${endpoint}/configurations/count`, args, options, fetch);
}

export function useCheckConfigurations<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; name?: string; isEnabled?: boolean; isDeleted?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('Configurations', `${endpoint}/configurations/check`, args, options, fetch);
}
