/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, ConfigCategories } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateConfigCategories(options?: Omit<(UseMutationOptions<(ConfigCategories | undefined), DefaultError, Prisma.ConfigCategoriesCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigCategoriesCreateArgs, DefaultError, ConfigCategories, true>('ConfigCategories', 'POST', `${endpoint}/configCategories/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigCategoriesCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigCategoriesCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ConfigCategories, Prisma.ConfigCategoriesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigCategoriesCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ConfigCategories, Prisma.ConfigCategoriesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyConfigCategories(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ConfigCategoriesCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigCategoriesCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ConfigCategories', 'POST', `${endpoint}/configCategories/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigCategoriesCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigCategoriesCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ConfigCategoriesCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyConfigCategories<TArgs extends Prisma.ConfigCategoriesFindManyArgs, TQueryFnData = Array<Prisma.ConfigCategoriesGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/findMany`, args, options, fetch);
}

export function useInfiniteFindManyConfigCategories<TArgs extends Prisma.ConfigCategoriesFindManyArgs, TQueryFnData = Array<Prisma.ConfigCategoriesGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/findMany`, args, options, fetch);
}

export function useSuspenseFindManyConfigCategories<TArgs extends Prisma.ConfigCategoriesFindManyArgs, TQueryFnData = Array<Prisma.ConfigCategoriesGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyConfigCategories<TArgs extends Prisma.ConfigCategoriesFindManyArgs, TQueryFnData = Array<Prisma.ConfigCategoriesGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/findMany`, args, options, fetch);
}

export function useFindUniqueConfigCategories<TArgs extends Prisma.ConfigCategoriesFindUniqueArgs, TQueryFnData = Prisma.ConfigCategoriesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueConfigCategories<TArgs extends Prisma.ConfigCategoriesFindUniqueArgs, TQueryFnData = Prisma.ConfigCategoriesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/findUnique`, args, options, fetch);
}

export function useFindFirstConfigCategories<TArgs extends Prisma.ConfigCategoriesFindFirstArgs, TQueryFnData = Prisma.ConfigCategoriesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstConfigCategories<TArgs extends Prisma.ConfigCategoriesFindFirstArgs, TQueryFnData = Prisma.ConfigCategoriesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/findFirst`, args, options, fetch);
}

export function useUpdateConfigCategories(options?: Omit<(UseMutationOptions<(ConfigCategories | undefined), DefaultError, Prisma.ConfigCategoriesUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigCategoriesUpdateArgs, DefaultError, ConfigCategories, true>('ConfigCategories', 'PUT', `${endpoint}/configCategories/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigCategoriesUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigCategoriesUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ConfigCategories, Prisma.ConfigCategoriesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigCategoriesUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ConfigCategories, Prisma.ConfigCategoriesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyConfigCategories(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ConfigCategoriesUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigCategoriesUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ConfigCategories', 'PUT', `${endpoint}/configCategories/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigCategoriesUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigCategoriesUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ConfigCategoriesUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertConfigCategories(options?: Omit<(UseMutationOptions<(ConfigCategories | undefined), DefaultError, Prisma.ConfigCategoriesUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigCategoriesUpsertArgs, DefaultError, ConfigCategories, true>('ConfigCategories', 'POST', `${endpoint}/configCategories/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigCategoriesUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigCategoriesUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ConfigCategories, Prisma.ConfigCategoriesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigCategoriesUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ConfigCategories, Prisma.ConfigCategoriesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteConfigCategories(options?: Omit<(UseMutationOptions<(ConfigCategories | undefined), DefaultError, Prisma.ConfigCategoriesDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigCategoriesDeleteArgs, DefaultError, ConfigCategories, true>('ConfigCategories', 'DELETE', `${endpoint}/configCategories/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigCategoriesDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigCategoriesDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ConfigCategories, Prisma.ConfigCategoriesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigCategoriesDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ConfigCategories, Prisma.ConfigCategoriesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyConfigCategories(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ConfigCategoriesDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigCategoriesDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ConfigCategories', 'DELETE', `${endpoint}/configCategories/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigCategoriesDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigCategoriesDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ConfigCategoriesDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateConfigCategories<TArgs extends Prisma.ConfigCategoriesAggregateArgs, TQueryFnData = Prisma.GetConfigCategoriesAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateConfigCategories<TArgs extends Prisma.ConfigCategoriesAggregateArgs, TQueryFnData = Prisma.GetConfigCategoriesAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/aggregate`, args, options, fetch);
}

export function useGroupByConfigCategories<TArgs extends Prisma.ConfigCategoriesGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ConfigCategoriesGroupByArgs['orderBy'] } : { orderBy?: Prisma.ConfigCategoriesGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ConfigCategoriesGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ConfigCategoriesGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigCategoriesGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigCategoriesGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ConfigCategoriesGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByConfigCategories<TArgs extends Prisma.ConfigCategoriesGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ConfigCategoriesGroupByArgs['orderBy'] } : { orderBy?: Prisma.ConfigCategoriesGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ConfigCategoriesGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ConfigCategoriesGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigCategoriesGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigCategoriesGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ConfigCategoriesGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/groupBy`, args, options, fetch);
}

export function useCountConfigCategories<TArgs extends Prisma.ConfigCategoriesCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ConfigCategoriesCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/count`, args, options, fetch);
}

export function useSuspenseCountConfigCategories<TArgs extends Prisma.ConfigCategoriesCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ConfigCategoriesCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigCategoriesCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigCategories', `${endpoint}/configCategories/count`, args, options, fetch);
}

export function useCheckConfigCategories<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; name?: string; isDeleted?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ConfigCategories', `${endpoint}/configCategories/check`, args, options, fetch);
}
