/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, ConfigVariants } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateConfigVariants(options?: Omit<(UseMutationOptions<(ConfigVariants | undefined), DefaultError, Prisma.ConfigVariantsCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigVariantsCreateArgs, DefaultError, ConfigVariants, true>('ConfigVariants', 'POST', `${endpoint}/configVariants/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigVariantsCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigVariantsCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ConfigVariants, Prisma.ConfigVariantsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigVariantsCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ConfigVariants, Prisma.ConfigVariantsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyConfigVariants(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ConfigVariantsCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigVariantsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ConfigVariants', 'POST', `${endpoint}/configVariants/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigVariantsCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigVariantsCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ConfigVariantsCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyConfigVariants<TArgs extends Prisma.ConfigVariantsFindManyArgs, TQueryFnData = Array<Prisma.ConfigVariantsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/findMany`, args, options, fetch);
}

export function useInfiniteFindManyConfigVariants<TArgs extends Prisma.ConfigVariantsFindManyArgs, TQueryFnData = Array<Prisma.ConfigVariantsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/findMany`, args, options, fetch);
}

export function useSuspenseFindManyConfigVariants<TArgs extends Prisma.ConfigVariantsFindManyArgs, TQueryFnData = Array<Prisma.ConfigVariantsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyConfigVariants<TArgs extends Prisma.ConfigVariantsFindManyArgs, TQueryFnData = Array<Prisma.ConfigVariantsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/findMany`, args, options, fetch);
}

export function useFindUniqueConfigVariants<TArgs extends Prisma.ConfigVariantsFindUniqueArgs, TQueryFnData = Prisma.ConfigVariantsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueConfigVariants<TArgs extends Prisma.ConfigVariantsFindUniqueArgs, TQueryFnData = Prisma.ConfigVariantsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/findUnique`, args, options, fetch);
}

export function useFindFirstConfigVariants<TArgs extends Prisma.ConfigVariantsFindFirstArgs, TQueryFnData = Prisma.ConfigVariantsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstConfigVariants<TArgs extends Prisma.ConfigVariantsFindFirstArgs, TQueryFnData = Prisma.ConfigVariantsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/findFirst`, args, options, fetch);
}

export function useUpdateConfigVariants(options?: Omit<(UseMutationOptions<(ConfigVariants | undefined), DefaultError, Prisma.ConfigVariantsUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigVariantsUpdateArgs, DefaultError, ConfigVariants, true>('ConfigVariants', 'PUT', `${endpoint}/configVariants/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigVariantsUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigVariantsUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ConfigVariants, Prisma.ConfigVariantsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigVariantsUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ConfigVariants, Prisma.ConfigVariantsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyConfigVariants(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ConfigVariantsUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigVariantsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ConfigVariants', 'PUT', `${endpoint}/configVariants/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigVariantsUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigVariantsUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ConfigVariantsUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertConfigVariants(options?: Omit<(UseMutationOptions<(ConfigVariants | undefined), DefaultError, Prisma.ConfigVariantsUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigVariantsUpsertArgs, DefaultError, ConfigVariants, true>('ConfigVariants', 'POST', `${endpoint}/configVariants/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigVariantsUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigVariantsUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ConfigVariants, Prisma.ConfigVariantsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigVariantsUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ConfigVariants, Prisma.ConfigVariantsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteConfigVariants(options?: Omit<(UseMutationOptions<(ConfigVariants | undefined), DefaultError, Prisma.ConfigVariantsDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigVariantsDeleteArgs, DefaultError, ConfigVariants, true>('ConfigVariants', 'DELETE', `${endpoint}/configVariants/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigVariantsDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigVariantsDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ConfigVariants, Prisma.ConfigVariantsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ConfigVariantsDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ConfigVariants, Prisma.ConfigVariantsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyConfigVariants(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ConfigVariantsDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ConfigVariantsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ConfigVariants', 'DELETE', `${endpoint}/configVariants/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ConfigVariantsDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ConfigVariantsDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ConfigVariantsDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateConfigVariants<TArgs extends Prisma.ConfigVariantsAggregateArgs, TQueryFnData = Prisma.GetConfigVariantsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateConfigVariants<TArgs extends Prisma.ConfigVariantsAggregateArgs, TQueryFnData = Prisma.GetConfigVariantsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/aggregate`, args, options, fetch);
}

export function useGroupByConfigVariants<TArgs extends Prisma.ConfigVariantsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ConfigVariantsGroupByArgs['orderBy'] } : { orderBy?: Prisma.ConfigVariantsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ConfigVariantsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ConfigVariantsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigVariantsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigVariantsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ConfigVariantsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByConfigVariants<TArgs extends Prisma.ConfigVariantsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ConfigVariantsGroupByArgs['orderBy'] } : { orderBy?: Prisma.ConfigVariantsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ConfigVariantsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ConfigVariantsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigVariantsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ConfigVariantsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ConfigVariantsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/groupBy`, args, options, fetch);
}

export function useCountConfigVariants<TArgs extends Prisma.ConfigVariantsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ConfigVariantsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/count`, args, options, fetch);
}

export function useSuspenseCountConfigVariants<TArgs extends Prisma.ConfigVariantsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ConfigVariantsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ConfigVariantsCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ConfigVariants', `${endpoint}/configVariants/count`, args, options, fetch);
}

export function useCheckConfigVariants<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; name?: string; isEnabled?: boolean; isDeleted?: boolean; categoryId?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ConfigVariants', `${endpoint}/configVariants/check`, args, options, fetch);
}
