/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, JUnitTestStep } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateJUnitTestStep(options?: Omit<(UseMutationOptions<(JUnitTestStep | undefined), DefaultError, Prisma.JUnitTestStepCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JUnitTestStepCreateArgs, DefaultError, JUnitTestStep, true>('JUnitTestStep', 'POST', `${endpoint}/jUnitTestStep/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JUnitTestStepCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.JUnitTestStepCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, JUnitTestStep, Prisma.JUnitTestStepGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.JUnitTestStepCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, JUnitTestStep, Prisma.JUnitTestStepGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyJUnitTestStep(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.JUnitTestStepCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JUnitTestStepCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('JUnitTestStep', 'POST', `${endpoint}/jUnitTestStep/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JUnitTestStepCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.JUnitTestStepCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.JUnitTestStepCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyJUnitTestStep<TArgs extends Prisma.JUnitTestStepFindManyArgs, TQueryFnData = Array<Prisma.JUnitTestStepGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/findMany`, args, options, fetch);
}

export function useInfiniteFindManyJUnitTestStep<TArgs extends Prisma.JUnitTestStepFindManyArgs, TQueryFnData = Array<Prisma.JUnitTestStepGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/findMany`, args, options, fetch);
}

export function useSuspenseFindManyJUnitTestStep<TArgs extends Prisma.JUnitTestStepFindManyArgs, TQueryFnData = Array<Prisma.JUnitTestStepGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyJUnitTestStep<TArgs extends Prisma.JUnitTestStepFindManyArgs, TQueryFnData = Array<Prisma.JUnitTestStepGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/findMany`, args, options, fetch);
}

export function useFindUniqueJUnitTestStep<TArgs extends Prisma.JUnitTestStepFindUniqueArgs, TQueryFnData = Prisma.JUnitTestStepGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueJUnitTestStep<TArgs extends Prisma.JUnitTestStepFindUniqueArgs, TQueryFnData = Prisma.JUnitTestStepGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/findUnique`, args, options, fetch);
}

export function useFindFirstJUnitTestStep<TArgs extends Prisma.JUnitTestStepFindFirstArgs, TQueryFnData = Prisma.JUnitTestStepGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstJUnitTestStep<TArgs extends Prisma.JUnitTestStepFindFirstArgs, TQueryFnData = Prisma.JUnitTestStepGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/findFirst`, args, options, fetch);
}

export function useUpdateJUnitTestStep(options?: Omit<(UseMutationOptions<(JUnitTestStep | undefined), DefaultError, Prisma.JUnitTestStepUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JUnitTestStepUpdateArgs, DefaultError, JUnitTestStep, true>('JUnitTestStep', 'PUT', `${endpoint}/jUnitTestStep/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JUnitTestStepUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.JUnitTestStepUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, JUnitTestStep, Prisma.JUnitTestStepGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.JUnitTestStepUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, JUnitTestStep, Prisma.JUnitTestStepGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyJUnitTestStep(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.JUnitTestStepUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JUnitTestStepUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('JUnitTestStep', 'PUT', `${endpoint}/jUnitTestStep/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JUnitTestStepUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.JUnitTestStepUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.JUnitTestStepUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertJUnitTestStep(options?: Omit<(UseMutationOptions<(JUnitTestStep | undefined), DefaultError, Prisma.JUnitTestStepUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JUnitTestStepUpsertArgs, DefaultError, JUnitTestStep, true>('JUnitTestStep', 'POST', `${endpoint}/jUnitTestStep/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JUnitTestStepUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.JUnitTestStepUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, JUnitTestStep, Prisma.JUnitTestStepGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.JUnitTestStepUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, JUnitTestStep, Prisma.JUnitTestStepGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteJUnitTestStep(options?: Omit<(UseMutationOptions<(JUnitTestStep | undefined), DefaultError, Prisma.JUnitTestStepDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JUnitTestStepDeleteArgs, DefaultError, JUnitTestStep, true>('JUnitTestStep', 'DELETE', `${endpoint}/jUnitTestStep/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JUnitTestStepDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.JUnitTestStepDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, JUnitTestStep, Prisma.JUnitTestStepGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.JUnitTestStepDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, JUnitTestStep, Prisma.JUnitTestStepGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyJUnitTestStep(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.JUnitTestStepDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JUnitTestStepDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('JUnitTestStep', 'DELETE', `${endpoint}/jUnitTestStep/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JUnitTestStepDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.JUnitTestStepDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.JUnitTestStepDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateJUnitTestStep<TArgs extends Prisma.JUnitTestStepAggregateArgs, TQueryFnData = Prisma.GetJUnitTestStepAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateJUnitTestStep<TArgs extends Prisma.JUnitTestStepAggregateArgs, TQueryFnData = Prisma.GetJUnitTestStepAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/aggregate`, args, options, fetch);
}

export function useGroupByJUnitTestStep<TArgs extends Prisma.JUnitTestStepGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.JUnitTestStepGroupByArgs['orderBy'] } : { orderBy?: Prisma.JUnitTestStepGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.JUnitTestStepGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.JUnitTestStepGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.JUnitTestStepGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.JUnitTestStepGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.JUnitTestStepGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByJUnitTestStep<TArgs extends Prisma.JUnitTestStepGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.JUnitTestStepGroupByArgs['orderBy'] } : { orderBy?: Prisma.JUnitTestStepGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.JUnitTestStepGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.JUnitTestStepGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.JUnitTestStepGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.JUnitTestStepGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.JUnitTestStepGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/groupBy`, args, options, fetch);
}

export function useCountJUnitTestStep<TArgs extends Prisma.JUnitTestStepCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.JUnitTestStepCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/count`, args, options, fetch);
}

export function useSuspenseCountJUnitTestStep<TArgs extends Prisma.JUnitTestStepCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.JUnitTestStepCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JUnitTestStepCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/count`, args, options, fetch);
}

export function useCheckJUnitTestStep<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; name?: string; content?: string; statusId?: number; repositoryCaseId?: number; createdById?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('JUnitTestStep', `${endpoint}/jUnitTestStep/check`, args, options, fetch);
}
