/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, LlmRateLimit } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateLlmRateLimit(options?: Omit<(UseMutationOptions<(LlmRateLimit | undefined), DefaultError, Prisma.LlmRateLimitCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmRateLimitCreateArgs, DefaultError, LlmRateLimit, true>('LlmRateLimit', 'POST', `${endpoint}/llmRateLimit/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmRateLimitCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmRateLimitCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmRateLimit, Prisma.LlmRateLimitGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmRateLimitCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmRateLimit, Prisma.LlmRateLimitGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyLlmRateLimit(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LlmRateLimitCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmRateLimitCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('LlmRateLimit', 'POST', `${endpoint}/llmRateLimit/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmRateLimitCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmRateLimitCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LlmRateLimitCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyLlmRateLimit<TArgs extends Prisma.LlmRateLimitFindManyArgs, TQueryFnData = Array<Prisma.LlmRateLimitGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/findMany`, args, options, fetch);
}

export function useInfiniteFindManyLlmRateLimit<TArgs extends Prisma.LlmRateLimitFindManyArgs, TQueryFnData = Array<Prisma.LlmRateLimitGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/findMany`, args, options, fetch);
}

export function useSuspenseFindManyLlmRateLimit<TArgs extends Prisma.LlmRateLimitFindManyArgs, TQueryFnData = Array<Prisma.LlmRateLimitGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyLlmRateLimit<TArgs extends Prisma.LlmRateLimitFindManyArgs, TQueryFnData = Array<Prisma.LlmRateLimitGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/findMany`, args, options, fetch);
}

export function useFindUniqueLlmRateLimit<TArgs extends Prisma.LlmRateLimitFindUniqueArgs, TQueryFnData = Prisma.LlmRateLimitGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueLlmRateLimit<TArgs extends Prisma.LlmRateLimitFindUniqueArgs, TQueryFnData = Prisma.LlmRateLimitGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/findUnique`, args, options, fetch);
}

export function useFindFirstLlmRateLimit<TArgs extends Prisma.LlmRateLimitFindFirstArgs, TQueryFnData = Prisma.LlmRateLimitGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstLlmRateLimit<TArgs extends Prisma.LlmRateLimitFindFirstArgs, TQueryFnData = Prisma.LlmRateLimitGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/findFirst`, args, options, fetch);
}

export function useUpdateLlmRateLimit(options?: Omit<(UseMutationOptions<(LlmRateLimit | undefined), DefaultError, Prisma.LlmRateLimitUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmRateLimitUpdateArgs, DefaultError, LlmRateLimit, true>('LlmRateLimit', 'PUT', `${endpoint}/llmRateLimit/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmRateLimitUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmRateLimitUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmRateLimit, Prisma.LlmRateLimitGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmRateLimitUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmRateLimit, Prisma.LlmRateLimitGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyLlmRateLimit(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LlmRateLimitUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmRateLimitUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('LlmRateLimit', 'PUT', `${endpoint}/llmRateLimit/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmRateLimitUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmRateLimitUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LlmRateLimitUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertLlmRateLimit(options?: Omit<(UseMutationOptions<(LlmRateLimit | undefined), DefaultError, Prisma.LlmRateLimitUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmRateLimitUpsertArgs, DefaultError, LlmRateLimit, true>('LlmRateLimit', 'POST', `${endpoint}/llmRateLimit/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmRateLimitUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmRateLimitUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmRateLimit, Prisma.LlmRateLimitGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmRateLimitUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmRateLimit, Prisma.LlmRateLimitGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteLlmRateLimit(options?: Omit<(UseMutationOptions<(LlmRateLimit | undefined), DefaultError, Prisma.LlmRateLimitDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmRateLimitDeleteArgs, DefaultError, LlmRateLimit, true>('LlmRateLimit', 'DELETE', `${endpoint}/llmRateLimit/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmRateLimitDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmRateLimitDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmRateLimit, Prisma.LlmRateLimitGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmRateLimitDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmRateLimit, Prisma.LlmRateLimitGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyLlmRateLimit(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LlmRateLimitDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmRateLimitDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('LlmRateLimit', 'DELETE', `${endpoint}/llmRateLimit/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmRateLimitDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmRateLimitDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LlmRateLimitDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateLlmRateLimit<TArgs extends Prisma.LlmRateLimitAggregateArgs, TQueryFnData = Prisma.GetLlmRateLimitAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateLlmRateLimit<TArgs extends Prisma.LlmRateLimitAggregateArgs, TQueryFnData = Prisma.GetLlmRateLimitAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/aggregate`, args, options, fetch);
}

export function useGroupByLlmRateLimit<TArgs extends Prisma.LlmRateLimitGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LlmRateLimitGroupByArgs['orderBy'] } : { orderBy?: Prisma.LlmRateLimitGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.LlmRateLimitGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.LlmRateLimitGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmRateLimitGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmRateLimitGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LlmRateLimitGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByLlmRateLimit<TArgs extends Prisma.LlmRateLimitGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LlmRateLimitGroupByArgs['orderBy'] } : { orderBy?: Prisma.LlmRateLimitGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.LlmRateLimitGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.LlmRateLimitGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmRateLimitGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmRateLimitGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LlmRateLimitGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/groupBy`, args, options, fetch);
}

export function useCountLlmRateLimit<TArgs extends Prisma.LlmRateLimitCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LlmRateLimitCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/count`, args, options, fetch);
}

export function useSuspenseCountLlmRateLimit<TArgs extends Prisma.LlmRateLimitCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LlmRateLimitCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmRateLimitCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/count`, args, options, fetch);
}

export function useCheckLlmRateLimit<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; llmIntegrationId?: number; scope?: string; scopeId?: string; feature?: string; windowType?: string; windowSize?: number; maxRequests?: number; maxTokens?: number; currentRequests?: number; currentTokens?: number; blockOnExceed?: boolean; queueOnExceed?: boolean; alertOnExceed?: boolean; priority?: number; isActive?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('LlmRateLimit', `${endpoint}/llmRateLimit/check`, args, options, fetch);
}
