/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, LlmFeatureConfig } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateLlmFeatureConfig(options?: Omit<(UseMutationOptions<(LlmFeatureConfig | undefined), DefaultError, Prisma.LlmFeatureConfigCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmFeatureConfigCreateArgs, DefaultError, LlmFeatureConfig, true>('LlmFeatureConfig', 'POST', `${endpoint}/llmFeatureConfig/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmFeatureConfigCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmFeatureConfigCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmFeatureConfig, Prisma.LlmFeatureConfigGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmFeatureConfigCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmFeatureConfig, Prisma.LlmFeatureConfigGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyLlmFeatureConfig(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LlmFeatureConfigCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmFeatureConfigCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('LlmFeatureConfig', 'POST', `${endpoint}/llmFeatureConfig/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmFeatureConfigCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmFeatureConfigCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LlmFeatureConfigCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigFindManyArgs, TQueryFnData = Array<Prisma.LlmFeatureConfigGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/findMany`, args, options, fetch);
}

export function useInfiniteFindManyLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigFindManyArgs, TQueryFnData = Array<Prisma.LlmFeatureConfigGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/findMany`, args, options, fetch);
}

export function useSuspenseFindManyLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigFindManyArgs, TQueryFnData = Array<Prisma.LlmFeatureConfigGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigFindManyArgs, TQueryFnData = Array<Prisma.LlmFeatureConfigGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/findMany`, args, options, fetch);
}

export function useFindUniqueLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigFindUniqueArgs, TQueryFnData = Prisma.LlmFeatureConfigGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigFindUniqueArgs, TQueryFnData = Prisma.LlmFeatureConfigGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/findUnique`, args, options, fetch);
}

export function useFindFirstLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigFindFirstArgs, TQueryFnData = Prisma.LlmFeatureConfigGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigFindFirstArgs, TQueryFnData = Prisma.LlmFeatureConfigGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/findFirst`, args, options, fetch);
}

export function useUpdateLlmFeatureConfig(options?: Omit<(UseMutationOptions<(LlmFeatureConfig | undefined), DefaultError, Prisma.LlmFeatureConfigUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmFeatureConfigUpdateArgs, DefaultError, LlmFeatureConfig, true>('LlmFeatureConfig', 'PUT', `${endpoint}/llmFeatureConfig/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmFeatureConfigUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmFeatureConfigUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmFeatureConfig, Prisma.LlmFeatureConfigGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmFeatureConfigUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmFeatureConfig, Prisma.LlmFeatureConfigGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyLlmFeatureConfig(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LlmFeatureConfigUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmFeatureConfigUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('LlmFeatureConfig', 'PUT', `${endpoint}/llmFeatureConfig/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmFeatureConfigUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmFeatureConfigUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LlmFeatureConfigUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertLlmFeatureConfig(options?: Omit<(UseMutationOptions<(LlmFeatureConfig | undefined), DefaultError, Prisma.LlmFeatureConfigUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmFeatureConfigUpsertArgs, DefaultError, LlmFeatureConfig, true>('LlmFeatureConfig', 'POST', `${endpoint}/llmFeatureConfig/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmFeatureConfigUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmFeatureConfigUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmFeatureConfig, Prisma.LlmFeatureConfigGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmFeatureConfigUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmFeatureConfig, Prisma.LlmFeatureConfigGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteLlmFeatureConfig(options?: Omit<(UseMutationOptions<(LlmFeatureConfig | undefined), DefaultError, Prisma.LlmFeatureConfigDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmFeatureConfigDeleteArgs, DefaultError, LlmFeatureConfig, true>('LlmFeatureConfig', 'DELETE', `${endpoint}/llmFeatureConfig/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmFeatureConfigDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmFeatureConfigDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmFeatureConfig, Prisma.LlmFeatureConfigGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmFeatureConfigDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmFeatureConfig, Prisma.LlmFeatureConfigGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyLlmFeatureConfig(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LlmFeatureConfigDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmFeatureConfigDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('LlmFeatureConfig', 'DELETE', `${endpoint}/llmFeatureConfig/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmFeatureConfigDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmFeatureConfigDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LlmFeatureConfigDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigAggregateArgs, TQueryFnData = Prisma.GetLlmFeatureConfigAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigAggregateArgs, TQueryFnData = Prisma.GetLlmFeatureConfigAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/aggregate`, args, options, fetch);
}

export function useGroupByLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LlmFeatureConfigGroupByArgs['orderBy'] } : { orderBy?: Prisma.LlmFeatureConfigGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.LlmFeatureConfigGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.LlmFeatureConfigGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmFeatureConfigGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmFeatureConfigGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LlmFeatureConfigGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LlmFeatureConfigGroupByArgs['orderBy'] } : { orderBy?: Prisma.LlmFeatureConfigGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.LlmFeatureConfigGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.LlmFeatureConfigGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmFeatureConfigGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmFeatureConfigGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LlmFeatureConfigGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/groupBy`, args, options, fetch);
}

export function useCountLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LlmFeatureConfigCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/count`, args, options, fetch);
}

export function useSuspenseCountLlmFeatureConfig<TArgs extends Prisma.LlmFeatureConfigCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LlmFeatureConfigCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmFeatureConfigCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/count`, args, options, fetch);
}

export function useCheckLlmFeatureConfig<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; projectId?: number; feature?: string; enabled?: boolean; llmIntegrationId?: number; templateId?: string; model?: string; maxTokens?: number; autoTrigger?: boolean; outputFormat?: string; dailyLimit?: number; monthlyLimit?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('LlmFeatureConfig', `${endpoint}/llmFeatureConfig/check`, args, options, fetch);
}
