/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, OllamaModelRegistry } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateOllamaModelRegistry(options?: Omit<(UseMutationOptions<(OllamaModelRegistry | undefined), DefaultError, Prisma.OllamaModelRegistryCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OllamaModelRegistryCreateArgs, DefaultError, OllamaModelRegistry, true>('OllamaModelRegistry', 'POST', `${endpoint}/ollamaModelRegistry/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OllamaModelRegistryCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.OllamaModelRegistryCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OllamaModelRegistry, Prisma.OllamaModelRegistryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OllamaModelRegistryCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OllamaModelRegistry, Prisma.OllamaModelRegistryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyOllamaModelRegistry(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OllamaModelRegistryCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OllamaModelRegistryCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('OllamaModelRegistry', 'POST', `${endpoint}/ollamaModelRegistry/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OllamaModelRegistryCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OllamaModelRegistryCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OllamaModelRegistryCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryFindManyArgs, TQueryFnData = Array<Prisma.OllamaModelRegistryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/findMany`, args, options, fetch);
}

export function useInfiniteFindManyOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryFindManyArgs, TQueryFnData = Array<Prisma.OllamaModelRegistryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/findMany`, args, options, fetch);
}

export function useSuspenseFindManyOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryFindManyArgs, TQueryFnData = Array<Prisma.OllamaModelRegistryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryFindManyArgs, TQueryFnData = Array<Prisma.OllamaModelRegistryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/findMany`, args, options, fetch);
}

export function useFindUniqueOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryFindUniqueArgs, TQueryFnData = Prisma.OllamaModelRegistryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryFindUniqueArgs, TQueryFnData = Prisma.OllamaModelRegistryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/findUnique`, args, options, fetch);
}

export function useFindFirstOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryFindFirstArgs, TQueryFnData = Prisma.OllamaModelRegistryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryFindFirstArgs, TQueryFnData = Prisma.OllamaModelRegistryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/findFirst`, args, options, fetch);
}

export function useUpdateOllamaModelRegistry(options?: Omit<(UseMutationOptions<(OllamaModelRegistry | undefined), DefaultError, Prisma.OllamaModelRegistryUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OllamaModelRegistryUpdateArgs, DefaultError, OllamaModelRegistry, true>('OllamaModelRegistry', 'PUT', `${endpoint}/ollamaModelRegistry/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OllamaModelRegistryUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.OllamaModelRegistryUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OllamaModelRegistry, Prisma.OllamaModelRegistryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OllamaModelRegistryUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OllamaModelRegistry, Prisma.OllamaModelRegistryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyOllamaModelRegistry(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OllamaModelRegistryUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OllamaModelRegistryUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('OllamaModelRegistry', 'PUT', `${endpoint}/ollamaModelRegistry/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OllamaModelRegistryUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OllamaModelRegistryUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OllamaModelRegistryUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertOllamaModelRegistry(options?: Omit<(UseMutationOptions<(OllamaModelRegistry | undefined), DefaultError, Prisma.OllamaModelRegistryUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OllamaModelRegistryUpsertArgs, DefaultError, OllamaModelRegistry, true>('OllamaModelRegistry', 'POST', `${endpoint}/ollamaModelRegistry/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OllamaModelRegistryUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.OllamaModelRegistryUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OllamaModelRegistry, Prisma.OllamaModelRegistryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OllamaModelRegistryUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OllamaModelRegistry, Prisma.OllamaModelRegistryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteOllamaModelRegistry(options?: Omit<(UseMutationOptions<(OllamaModelRegistry | undefined), DefaultError, Prisma.OllamaModelRegistryDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OllamaModelRegistryDeleteArgs, DefaultError, OllamaModelRegistry, true>('OllamaModelRegistry', 'DELETE', `${endpoint}/ollamaModelRegistry/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OllamaModelRegistryDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.OllamaModelRegistryDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, OllamaModelRegistry, Prisma.OllamaModelRegistryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OllamaModelRegistryDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, OllamaModelRegistry, Prisma.OllamaModelRegistryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyOllamaModelRegistry(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OllamaModelRegistryDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OllamaModelRegistryDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('OllamaModelRegistry', 'DELETE', `${endpoint}/ollamaModelRegistry/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OllamaModelRegistryDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OllamaModelRegistryDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OllamaModelRegistryDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryAggregateArgs, TQueryFnData = Prisma.GetOllamaModelRegistryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryAggregateArgs, TQueryFnData = Prisma.GetOllamaModelRegistryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/aggregate`, args, options, fetch);
}

export function useGroupByOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.OllamaModelRegistryGroupByArgs['orderBy'] } : { orderBy?: Prisma.OllamaModelRegistryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.OllamaModelRegistryGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.OllamaModelRegistryGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.OllamaModelRegistryGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.OllamaModelRegistryGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.OllamaModelRegistryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.OllamaModelRegistryGroupByArgs['orderBy'] } : { orderBy?: Prisma.OllamaModelRegistryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.OllamaModelRegistryGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.OllamaModelRegistryGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.OllamaModelRegistryGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.OllamaModelRegistryGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.OllamaModelRegistryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/groupBy`, args, options, fetch);
}

export function useCountOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.OllamaModelRegistryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/count`, args, options, fetch);
}

export function useSuspenseCountOllamaModelRegistry<TArgs extends Prisma.OllamaModelRegistryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.OllamaModelRegistryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.OllamaModelRegistryCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/count`, args, options, fetch);
}

export function useCheckOllamaModelRegistry<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; llmIntegrationId?: number; modelName?: string; modelTag?: string; modelSize?: number; digest?: string; contextWindow?: number; quantization?: string; isInstalled?: boolean; isPulling?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('OllamaModelRegistry', `${endpoint}/ollamaModelRegistry/check`, args, options, fetch);
}
