/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, SessionVersions } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateSessionVersions(options?: Omit<(UseMutationOptions<(SessionVersions | undefined), DefaultError, Prisma.SessionVersionsCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SessionVersionsCreateArgs, DefaultError, SessionVersions, true>('SessionVersions', 'POST', `${endpoint}/sessionVersions/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SessionVersionsCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.SessionVersionsCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, SessionVersions, Prisma.SessionVersionsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SessionVersionsCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, SessionVersions, Prisma.SessionVersionsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManySessionVersions(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SessionVersionsCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SessionVersionsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('SessionVersions', 'POST', `${endpoint}/sessionVersions/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SessionVersionsCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.SessionVersionsCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SessionVersionsCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManySessionVersions<TArgs extends Prisma.SessionVersionsFindManyArgs, TQueryFnData = Array<Prisma.SessionVersionsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/findMany`, args, options, fetch);
}

export function useInfiniteFindManySessionVersions<TArgs extends Prisma.SessionVersionsFindManyArgs, TQueryFnData = Array<Prisma.SessionVersionsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/findMany`, args, options, fetch);
}

export function useSuspenseFindManySessionVersions<TArgs extends Prisma.SessionVersionsFindManyArgs, TQueryFnData = Array<Prisma.SessionVersionsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManySessionVersions<TArgs extends Prisma.SessionVersionsFindManyArgs, TQueryFnData = Array<Prisma.SessionVersionsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/findMany`, args, options, fetch);
}

export function useFindUniqueSessionVersions<TArgs extends Prisma.SessionVersionsFindUniqueArgs, TQueryFnData = Prisma.SessionVersionsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueSessionVersions<TArgs extends Prisma.SessionVersionsFindUniqueArgs, TQueryFnData = Prisma.SessionVersionsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/findUnique`, args, options, fetch);
}

export function useFindFirstSessionVersions<TArgs extends Prisma.SessionVersionsFindFirstArgs, TQueryFnData = Prisma.SessionVersionsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstSessionVersions<TArgs extends Prisma.SessionVersionsFindFirstArgs, TQueryFnData = Prisma.SessionVersionsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/findFirst`, args, options, fetch);
}

export function useUpdateSessionVersions(options?: Omit<(UseMutationOptions<(SessionVersions | undefined), DefaultError, Prisma.SessionVersionsUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SessionVersionsUpdateArgs, DefaultError, SessionVersions, true>('SessionVersions', 'PUT', `${endpoint}/sessionVersions/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SessionVersionsUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.SessionVersionsUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, SessionVersions, Prisma.SessionVersionsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SessionVersionsUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, SessionVersions, Prisma.SessionVersionsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManySessionVersions(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SessionVersionsUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SessionVersionsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('SessionVersions', 'PUT', `${endpoint}/sessionVersions/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SessionVersionsUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.SessionVersionsUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SessionVersionsUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertSessionVersions(options?: Omit<(UseMutationOptions<(SessionVersions | undefined), DefaultError, Prisma.SessionVersionsUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SessionVersionsUpsertArgs, DefaultError, SessionVersions, true>('SessionVersions', 'POST', `${endpoint}/sessionVersions/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SessionVersionsUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.SessionVersionsUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, SessionVersions, Prisma.SessionVersionsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SessionVersionsUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, SessionVersions, Prisma.SessionVersionsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteSessionVersions(options?: Omit<(UseMutationOptions<(SessionVersions | undefined), DefaultError, Prisma.SessionVersionsDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SessionVersionsDeleteArgs, DefaultError, SessionVersions, true>('SessionVersions', 'DELETE', `${endpoint}/sessionVersions/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SessionVersionsDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.SessionVersionsDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, SessionVersions, Prisma.SessionVersionsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SessionVersionsDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, SessionVersions, Prisma.SessionVersionsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManySessionVersions(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SessionVersionsDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SessionVersionsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('SessionVersions', 'DELETE', `${endpoint}/sessionVersions/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SessionVersionsDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.SessionVersionsDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SessionVersionsDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateSessionVersions<TArgs extends Prisma.SessionVersionsAggregateArgs, TQueryFnData = Prisma.GetSessionVersionsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateSessionVersions<TArgs extends Prisma.SessionVersionsAggregateArgs, TQueryFnData = Prisma.GetSessionVersionsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/aggregate`, args, options, fetch);
}

export function useGroupBySessionVersions<TArgs extends Prisma.SessionVersionsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.SessionVersionsGroupByArgs['orderBy'] } : { orderBy?: Prisma.SessionVersionsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.SessionVersionsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.SessionVersionsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.SessionVersionsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.SessionVersionsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.SessionVersionsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/groupBy`, args, options, fetch);
}

export function useSuspenseGroupBySessionVersions<TArgs extends Prisma.SessionVersionsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.SessionVersionsGroupByArgs['orderBy'] } : { orderBy?: Prisma.SessionVersionsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.SessionVersionsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.SessionVersionsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.SessionVersionsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.SessionVersionsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.SessionVersionsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/groupBy`, args, options, fetch);
}

export function useCountSessionVersions<TArgs extends Prisma.SessionVersionsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.SessionVersionsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/count`, args, options, fetch);
}

export function useSuspenseCountSessionVersions<TArgs extends Prisma.SessionVersionsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.SessionVersionsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.SessionVersionsCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('SessionVersions', `${endpoint}/sessionVersions/count`, args, options, fetch);
}

export function useCheckSessionVersions<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; sessionId?: number; name?: string; staticProjectId?: number; staticProjectName?: string; projectId?: number; templateId?: number; templateName?: string; configId?: number; configurationName?: string; milestoneId?: number; milestoneName?: string; stateId?: number; stateName?: string; assignedToId?: string; assignedToName?: string; createdById?: string; createdByName?: string; estimate?: number; forecastManual?: number; elapsed?: number; isCompleted?: boolean; version?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('SessionVersions', `${endpoint}/sessionVersions/check`, args, options, fetch);
}
