/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, StatusScope } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateStatusScope(options?: Omit<(UseMutationOptions<(StatusScope | undefined), DefaultError, Prisma.StatusScopeCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StatusScopeCreateArgs, DefaultError, StatusScope, true>('StatusScope', 'POST', `${endpoint}/statusScope/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StatusScopeCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.StatusScopeCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StatusScope, Prisma.StatusScopeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StatusScopeCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StatusScope, Prisma.StatusScopeGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyStatusScope(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.StatusScopeCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StatusScopeCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('StatusScope', 'POST', `${endpoint}/statusScope/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StatusScopeCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.StatusScopeCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.StatusScopeCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyStatusScope<TArgs extends Prisma.StatusScopeFindManyArgs, TQueryFnData = Array<Prisma.StatusScopeGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StatusScopeFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/findMany`, args, options, fetch);
}

export function useInfiniteFindManyStatusScope<TArgs extends Prisma.StatusScopeFindManyArgs, TQueryFnData = Array<Prisma.StatusScopeGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StatusScopeFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/findMany`, args, options, fetch);
}

export function useSuspenseFindManyStatusScope<TArgs extends Prisma.StatusScopeFindManyArgs, TQueryFnData = Array<Prisma.StatusScopeGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StatusScopeFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyStatusScope<TArgs extends Prisma.StatusScopeFindManyArgs, TQueryFnData = Array<Prisma.StatusScopeGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StatusScopeFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/findMany`, args, options, fetch);
}

export function useFindUniqueStatusScope<TArgs extends Prisma.StatusScopeFindUniqueArgs, TQueryFnData = Prisma.StatusScopeGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StatusScopeFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueStatusScope<TArgs extends Prisma.StatusScopeFindUniqueArgs, TQueryFnData = Prisma.StatusScopeGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StatusScopeFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/findUnique`, args, options, fetch);
}

export function useFindFirstStatusScope<TArgs extends Prisma.StatusScopeFindFirstArgs, TQueryFnData = Prisma.StatusScopeGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StatusScopeFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstStatusScope<TArgs extends Prisma.StatusScopeFindFirstArgs, TQueryFnData = Prisma.StatusScopeGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StatusScopeFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/findFirst`, args, options, fetch);
}

export function useUpdateStatusScope(options?: Omit<(UseMutationOptions<(StatusScope | undefined), DefaultError, Prisma.StatusScopeUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StatusScopeUpdateArgs, DefaultError, StatusScope, true>('StatusScope', 'PUT', `${endpoint}/statusScope/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StatusScopeUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.StatusScopeUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StatusScope, Prisma.StatusScopeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StatusScopeUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StatusScope, Prisma.StatusScopeGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyStatusScope(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.StatusScopeUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StatusScopeUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('StatusScope', 'PUT', `${endpoint}/statusScope/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StatusScopeUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.StatusScopeUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.StatusScopeUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertStatusScope(options?: Omit<(UseMutationOptions<(StatusScope | undefined), DefaultError, Prisma.StatusScopeUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StatusScopeUpsertArgs, DefaultError, StatusScope, true>('StatusScope', 'POST', `${endpoint}/statusScope/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StatusScopeUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.StatusScopeUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StatusScope, Prisma.StatusScopeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StatusScopeUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StatusScope, Prisma.StatusScopeGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteStatusScope(options?: Omit<(UseMutationOptions<(StatusScope | undefined), DefaultError, Prisma.StatusScopeDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StatusScopeDeleteArgs, DefaultError, StatusScope, true>('StatusScope', 'DELETE', `${endpoint}/statusScope/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StatusScopeDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.StatusScopeDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StatusScope, Prisma.StatusScopeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StatusScopeDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StatusScope, Prisma.StatusScopeGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyStatusScope(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.StatusScopeDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StatusScopeDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('StatusScope', 'DELETE', `${endpoint}/statusScope/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StatusScopeDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.StatusScopeDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.StatusScopeDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateStatusScope<TArgs extends Prisma.StatusScopeAggregateArgs, TQueryFnData = Prisma.GetStatusScopeAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StatusScopeAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateStatusScope<TArgs extends Prisma.StatusScopeAggregateArgs, TQueryFnData = Prisma.GetStatusScopeAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StatusScopeAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/aggregate`, args, options, fetch);
}

export function useGroupByStatusScope<TArgs extends Prisma.StatusScopeGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.StatusScopeGroupByArgs['orderBy'] } : { orderBy?: Prisma.StatusScopeGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.StatusScopeGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.StatusScopeGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.StatusScopeGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.StatusScopeGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.StatusScopeGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByStatusScope<TArgs extends Prisma.StatusScopeGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.StatusScopeGroupByArgs['orderBy'] } : { orderBy?: Prisma.StatusScopeGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.StatusScopeGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.StatusScopeGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.StatusScopeGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.StatusScopeGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.StatusScopeGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/groupBy`, args, options, fetch);
}

export function useCountStatusScope<TArgs extends Prisma.StatusScopeCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.StatusScopeCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StatusScopeCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/count`, args, options, fetch);
}

export function useSuspenseCountStatusScope<TArgs extends Prisma.StatusScopeCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.StatusScopeCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StatusScopeCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StatusScope', `${endpoint}/statusScope/count`, args, options, fetch);
}

export function useCheckStatusScope<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; name?: string; icon?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('StatusScope', `${endpoint}/statusScope/check`, args, options, fetch);
}
