/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, TemplateProjectAssignment } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateTemplateProjectAssignment(options?: Omit<(UseMutationOptions<(TemplateProjectAssignment | undefined), DefaultError, Prisma.TemplateProjectAssignmentCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateProjectAssignmentCreateArgs, DefaultError, TemplateProjectAssignment, true>('TemplateProjectAssignment', 'POST', `${endpoint}/templateProjectAssignment/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateProjectAssignmentCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TemplateProjectAssignment, Prisma.TemplateProjectAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TemplateProjectAssignment, Prisma.TemplateProjectAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyTemplateProjectAssignment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TemplateProjectAssignmentCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateProjectAssignmentCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('TemplateProjectAssignment', 'POST', `${endpoint}/templateProjectAssignment/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateProjectAssignmentCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentFindManyArgs, TQueryFnData = Array<Prisma.TemplateProjectAssignmentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentFindManyArgs, TQueryFnData = Array<Prisma.TemplateProjectAssignmentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentFindManyArgs, TQueryFnData = Array<Prisma.TemplateProjectAssignmentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentFindManyArgs, TQueryFnData = Array<Prisma.TemplateProjectAssignmentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/findMany`, args, options, fetch);
}

export function useFindUniqueTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentFindUniqueArgs, TQueryFnData = Prisma.TemplateProjectAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentFindUniqueArgs, TQueryFnData = Prisma.TemplateProjectAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/findUnique`, args, options, fetch);
}

export function useFindFirstTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentFindFirstArgs, TQueryFnData = Prisma.TemplateProjectAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentFindFirstArgs, TQueryFnData = Prisma.TemplateProjectAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/findFirst`, args, options, fetch);
}

export function useUpdateTemplateProjectAssignment(options?: Omit<(UseMutationOptions<(TemplateProjectAssignment | undefined), DefaultError, Prisma.TemplateProjectAssignmentUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateProjectAssignmentUpdateArgs, DefaultError, TemplateProjectAssignment, true>('TemplateProjectAssignment', 'PUT', `${endpoint}/templateProjectAssignment/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateProjectAssignmentUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TemplateProjectAssignment, Prisma.TemplateProjectAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TemplateProjectAssignment, Prisma.TemplateProjectAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyTemplateProjectAssignment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TemplateProjectAssignmentUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateProjectAssignmentUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('TemplateProjectAssignment', 'PUT', `${endpoint}/templateProjectAssignment/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateProjectAssignmentUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertTemplateProjectAssignment(options?: Omit<(UseMutationOptions<(TemplateProjectAssignment | undefined), DefaultError, Prisma.TemplateProjectAssignmentUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateProjectAssignmentUpsertArgs, DefaultError, TemplateProjectAssignment, true>('TemplateProjectAssignment', 'POST', `${endpoint}/templateProjectAssignment/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateProjectAssignmentUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TemplateProjectAssignment, Prisma.TemplateProjectAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TemplateProjectAssignment, Prisma.TemplateProjectAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteTemplateProjectAssignment(options?: Omit<(UseMutationOptions<(TemplateProjectAssignment | undefined), DefaultError, Prisma.TemplateProjectAssignmentDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateProjectAssignmentDeleteArgs, DefaultError, TemplateProjectAssignment, true>('TemplateProjectAssignment', 'DELETE', `${endpoint}/templateProjectAssignment/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateProjectAssignmentDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TemplateProjectAssignment, Prisma.TemplateProjectAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TemplateProjectAssignment, Prisma.TemplateProjectAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyTemplateProjectAssignment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TemplateProjectAssignmentDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateProjectAssignmentDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('TemplateProjectAssignment', 'DELETE', `${endpoint}/templateProjectAssignment/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateProjectAssignmentDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TemplateProjectAssignmentDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentAggregateArgs, TQueryFnData = Prisma.GetTemplateProjectAssignmentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentAggregateArgs, TQueryFnData = Prisma.GetTemplateProjectAssignmentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/aggregate`, args, options, fetch);
}

export function useGroupByTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TemplateProjectAssignmentGroupByArgs['orderBy'] } : { orderBy?: Prisma.TemplateProjectAssignmentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TemplateProjectAssignmentGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TemplateProjectAssignmentGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TemplateProjectAssignmentGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TemplateProjectAssignmentGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TemplateProjectAssignmentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TemplateProjectAssignmentGroupByArgs['orderBy'] } : { orderBy?: Prisma.TemplateProjectAssignmentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TemplateProjectAssignmentGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TemplateProjectAssignmentGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TemplateProjectAssignmentGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TemplateProjectAssignmentGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TemplateProjectAssignmentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/groupBy`, args, options, fetch);
}

export function useCountTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TemplateProjectAssignmentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/count`, args, options, fetch);
}

export function useSuspenseCountTemplateProjectAssignment<TArgs extends Prisma.TemplateProjectAssignmentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TemplateProjectAssignmentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateProjectAssignmentCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/count`, args, options, fetch);
}

export function useCheckTemplateProjectAssignment<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { templateId?: number; projectId?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('TemplateProjectAssignment', `${endpoint}/templateProjectAssignment/check`, args, options, fetch);
}
