/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, TemplateCaseAssignment } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateTemplateCaseAssignment(options?: Omit<(UseMutationOptions<(TemplateCaseAssignment | undefined), DefaultError, Prisma.TemplateCaseAssignmentCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateCaseAssignmentCreateArgs, DefaultError, TemplateCaseAssignment, true>('TemplateCaseAssignment', 'POST', `${endpoint}/templateCaseAssignment/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateCaseAssignmentCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TemplateCaseAssignment, Prisma.TemplateCaseAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TemplateCaseAssignment, Prisma.TemplateCaseAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyTemplateCaseAssignment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TemplateCaseAssignmentCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateCaseAssignmentCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('TemplateCaseAssignment', 'POST', `${endpoint}/templateCaseAssignment/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateCaseAssignmentCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentFindManyArgs, TQueryFnData = Array<Prisma.TemplateCaseAssignmentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentFindManyArgs, TQueryFnData = Array<Prisma.TemplateCaseAssignmentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentFindManyArgs, TQueryFnData = Array<Prisma.TemplateCaseAssignmentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentFindManyArgs, TQueryFnData = Array<Prisma.TemplateCaseAssignmentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/findMany`, args, options, fetch);
}

export function useFindUniqueTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentFindUniqueArgs, TQueryFnData = Prisma.TemplateCaseAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentFindUniqueArgs, TQueryFnData = Prisma.TemplateCaseAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/findUnique`, args, options, fetch);
}

export function useFindFirstTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentFindFirstArgs, TQueryFnData = Prisma.TemplateCaseAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentFindFirstArgs, TQueryFnData = Prisma.TemplateCaseAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/findFirst`, args, options, fetch);
}

export function useUpdateTemplateCaseAssignment(options?: Omit<(UseMutationOptions<(TemplateCaseAssignment | undefined), DefaultError, Prisma.TemplateCaseAssignmentUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateCaseAssignmentUpdateArgs, DefaultError, TemplateCaseAssignment, true>('TemplateCaseAssignment', 'PUT', `${endpoint}/templateCaseAssignment/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateCaseAssignmentUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TemplateCaseAssignment, Prisma.TemplateCaseAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TemplateCaseAssignment, Prisma.TemplateCaseAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyTemplateCaseAssignment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TemplateCaseAssignmentUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateCaseAssignmentUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('TemplateCaseAssignment', 'PUT', `${endpoint}/templateCaseAssignment/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateCaseAssignmentUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertTemplateCaseAssignment(options?: Omit<(UseMutationOptions<(TemplateCaseAssignment | undefined), DefaultError, Prisma.TemplateCaseAssignmentUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateCaseAssignmentUpsertArgs, DefaultError, TemplateCaseAssignment, true>('TemplateCaseAssignment', 'POST', `${endpoint}/templateCaseAssignment/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateCaseAssignmentUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TemplateCaseAssignment, Prisma.TemplateCaseAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TemplateCaseAssignment, Prisma.TemplateCaseAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteTemplateCaseAssignment(options?: Omit<(UseMutationOptions<(TemplateCaseAssignment | undefined), DefaultError, Prisma.TemplateCaseAssignmentDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateCaseAssignmentDeleteArgs, DefaultError, TemplateCaseAssignment, true>('TemplateCaseAssignment', 'DELETE', `${endpoint}/templateCaseAssignment/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateCaseAssignmentDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TemplateCaseAssignment, Prisma.TemplateCaseAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TemplateCaseAssignment, Prisma.TemplateCaseAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyTemplateCaseAssignment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TemplateCaseAssignmentDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TemplateCaseAssignmentDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('TemplateCaseAssignment', 'DELETE', `${endpoint}/templateCaseAssignment/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TemplateCaseAssignmentDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TemplateCaseAssignmentDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentAggregateArgs, TQueryFnData = Prisma.GetTemplateCaseAssignmentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentAggregateArgs, TQueryFnData = Prisma.GetTemplateCaseAssignmentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/aggregate`, args, options, fetch);
}

export function useGroupByTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TemplateCaseAssignmentGroupByArgs['orderBy'] } : { orderBy?: Prisma.TemplateCaseAssignmentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TemplateCaseAssignmentGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TemplateCaseAssignmentGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TemplateCaseAssignmentGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TemplateCaseAssignmentGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TemplateCaseAssignmentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TemplateCaseAssignmentGroupByArgs['orderBy'] } : { orderBy?: Prisma.TemplateCaseAssignmentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TemplateCaseAssignmentGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TemplateCaseAssignmentGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TemplateCaseAssignmentGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TemplateCaseAssignmentGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TemplateCaseAssignmentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/groupBy`, args, options, fetch);
}

export function useCountTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TemplateCaseAssignmentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/count`, args, options, fetch);
}

export function useSuspenseCountTemplateCaseAssignment<TArgs extends Prisma.TemplateCaseAssignmentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TemplateCaseAssignmentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TemplateCaseAssignmentCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/count`, args, options, fetch);
}

export function useCheckTemplateCaseAssignment<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { caseFieldId?: number; templateId?: number; order?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('TemplateCaseAssignment', `${endpoint}/templateCaseAssignment/check`, args, options, fetch);
}
