/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, TestRuns } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateTestRuns(options?: Omit<(UseMutationOptions<(TestRuns | undefined), DefaultError, Prisma.TestRunsCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunsCreateArgs, DefaultError, TestRuns, true>('TestRuns', 'POST', `${endpoint}/testRuns/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunsCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunsCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestRuns, Prisma.TestRunsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestRunsCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestRuns, Prisma.TestRunsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyTestRuns(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestRunsCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('TestRuns', 'POST', `${endpoint}/testRuns/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunsCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunsCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestRunsCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyTestRuns<TArgs extends Prisma.TestRunsFindManyArgs, TQueryFnData = Array<Prisma.TestRunsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunsFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTestRuns<TArgs extends Prisma.TestRunsFindManyArgs, TQueryFnData = Array<Prisma.TestRunsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunsFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTestRuns<TArgs extends Prisma.TestRunsFindManyArgs, TQueryFnData = Array<Prisma.TestRunsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunsFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTestRuns<TArgs extends Prisma.TestRunsFindManyArgs, TQueryFnData = Array<Prisma.TestRunsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/findMany`, args, options, fetch);
}

export function useFindUniqueTestRuns<TArgs extends Prisma.TestRunsFindUniqueArgs, TQueryFnData = Prisma.TestRunsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestRunsFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTestRuns<TArgs extends Prisma.TestRunsFindUniqueArgs, TQueryFnData = Prisma.TestRunsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestRunsFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/findUnique`, args, options, fetch);
}

export function useFindFirstTestRuns<TArgs extends Prisma.TestRunsFindFirstArgs, TQueryFnData = Prisma.TestRunsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunsFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTestRuns<TArgs extends Prisma.TestRunsFindFirstArgs, TQueryFnData = Prisma.TestRunsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunsFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/findFirst`, args, options, fetch);
}

export function useUpdateTestRuns(options?: Omit<(UseMutationOptions<(TestRuns | undefined), DefaultError, Prisma.TestRunsUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunsUpdateArgs, DefaultError, TestRuns, true>('TestRuns', 'PUT', `${endpoint}/testRuns/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunsUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunsUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestRuns, Prisma.TestRunsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestRunsUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestRuns, Prisma.TestRunsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyTestRuns(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestRunsUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('TestRuns', 'PUT', `${endpoint}/testRuns/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunsUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunsUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestRunsUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertTestRuns(options?: Omit<(UseMutationOptions<(TestRuns | undefined), DefaultError, Prisma.TestRunsUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunsUpsertArgs, DefaultError, TestRuns, true>('TestRuns', 'POST', `${endpoint}/testRuns/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunsUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunsUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestRuns, Prisma.TestRunsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestRunsUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestRuns, Prisma.TestRunsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteTestRuns(options?: Omit<(UseMutationOptions<(TestRuns | undefined), DefaultError, Prisma.TestRunsDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunsDeleteArgs, DefaultError, TestRuns, true>('TestRuns', 'DELETE', `${endpoint}/testRuns/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunsDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunsDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestRuns, Prisma.TestRunsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestRunsDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestRuns, Prisma.TestRunsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyTestRuns(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestRunsDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('TestRuns', 'DELETE', `${endpoint}/testRuns/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunsDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunsDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestRunsDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateTestRuns<TArgs extends Prisma.TestRunsAggregateArgs, TQueryFnData = Prisma.GetTestRunsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestRunsAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTestRuns<TArgs extends Prisma.TestRunsAggregateArgs, TQueryFnData = Prisma.GetTestRunsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestRunsAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/aggregate`, args, options, fetch);
}

export function useGroupByTestRuns<TArgs extends Prisma.TestRunsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TestRunsGroupByArgs['orderBy'] } : { orderBy?: Prisma.TestRunsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TestRunsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TestRunsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TestRunsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TestRunsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TestRunsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTestRuns<TArgs extends Prisma.TestRunsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TestRunsGroupByArgs['orderBy'] } : { orderBy?: Prisma.TestRunsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TestRunsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TestRunsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TestRunsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TestRunsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TestRunsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/groupBy`, args, options, fetch);
}

export function useCountTestRuns<TArgs extends Prisma.TestRunsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TestRunsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunsCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/count`, args, options, fetch);
}

export function useSuspenseCountTestRuns<TArgs extends Prisma.TestRunsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TestRunsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunsCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRuns', `${endpoint}/testRuns/count`, args, options, fetch);
}
import type { TestRunType } from '@prisma/client';

export function useCheckTestRuns<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; projectId?: number; name?: string; configId?: number; milestoneId?: number; stateId?: number; forecastManual?: number; elapsed?: number; isCompleted?: boolean; isDeleted?: boolean; createdById?: string; testRunType?: TestRunType; configurationGroupId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('TestRuns', `${endpoint}/testRuns/check`, args, options, fetch);
}
