/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, TestmoImportJob } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateTestmoImportJob(options?: Omit<(UseMutationOptions<(TestmoImportJob | undefined), DefaultError, Prisma.TestmoImportJobCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestmoImportJobCreateArgs, DefaultError, TestmoImportJob, true>('TestmoImportJob', 'POST', `${endpoint}/testmoImportJob/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestmoImportJobCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestmoImportJobCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestmoImportJob, Prisma.TestmoImportJobGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestmoImportJobCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestmoImportJob, Prisma.TestmoImportJobGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyTestmoImportJob(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestmoImportJobCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestmoImportJobCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('TestmoImportJob', 'POST', `${endpoint}/testmoImportJob/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestmoImportJobCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestmoImportJobCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestmoImportJobCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyTestmoImportJob<TArgs extends Prisma.TestmoImportJobFindManyArgs, TQueryFnData = Array<Prisma.TestmoImportJobGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTestmoImportJob<TArgs extends Prisma.TestmoImportJobFindManyArgs, TQueryFnData = Array<Prisma.TestmoImportJobGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTestmoImportJob<TArgs extends Prisma.TestmoImportJobFindManyArgs, TQueryFnData = Array<Prisma.TestmoImportJobGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTestmoImportJob<TArgs extends Prisma.TestmoImportJobFindManyArgs, TQueryFnData = Array<Prisma.TestmoImportJobGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/findMany`, args, options, fetch);
}

export function useFindUniqueTestmoImportJob<TArgs extends Prisma.TestmoImportJobFindUniqueArgs, TQueryFnData = Prisma.TestmoImportJobGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTestmoImportJob<TArgs extends Prisma.TestmoImportJobFindUniqueArgs, TQueryFnData = Prisma.TestmoImportJobGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/findUnique`, args, options, fetch);
}

export function useFindFirstTestmoImportJob<TArgs extends Prisma.TestmoImportJobFindFirstArgs, TQueryFnData = Prisma.TestmoImportJobGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTestmoImportJob<TArgs extends Prisma.TestmoImportJobFindFirstArgs, TQueryFnData = Prisma.TestmoImportJobGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/findFirst`, args, options, fetch);
}

export function useUpdateTestmoImportJob(options?: Omit<(UseMutationOptions<(TestmoImportJob | undefined), DefaultError, Prisma.TestmoImportJobUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestmoImportJobUpdateArgs, DefaultError, TestmoImportJob, true>('TestmoImportJob', 'PUT', `${endpoint}/testmoImportJob/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestmoImportJobUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestmoImportJobUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestmoImportJob, Prisma.TestmoImportJobGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestmoImportJobUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestmoImportJob, Prisma.TestmoImportJobGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyTestmoImportJob(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestmoImportJobUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestmoImportJobUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('TestmoImportJob', 'PUT', `${endpoint}/testmoImportJob/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestmoImportJobUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestmoImportJobUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestmoImportJobUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertTestmoImportJob(options?: Omit<(UseMutationOptions<(TestmoImportJob | undefined), DefaultError, Prisma.TestmoImportJobUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestmoImportJobUpsertArgs, DefaultError, TestmoImportJob, true>('TestmoImportJob', 'POST', `${endpoint}/testmoImportJob/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestmoImportJobUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestmoImportJobUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestmoImportJob, Prisma.TestmoImportJobGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestmoImportJobUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestmoImportJob, Prisma.TestmoImportJobGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteTestmoImportJob(options?: Omit<(UseMutationOptions<(TestmoImportJob | undefined), DefaultError, Prisma.TestmoImportJobDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestmoImportJobDeleteArgs, DefaultError, TestmoImportJob, true>('TestmoImportJob', 'DELETE', `${endpoint}/testmoImportJob/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestmoImportJobDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestmoImportJobDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestmoImportJob, Prisma.TestmoImportJobGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestmoImportJobDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestmoImportJob, Prisma.TestmoImportJobGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyTestmoImportJob(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestmoImportJobDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestmoImportJobDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('TestmoImportJob', 'DELETE', `${endpoint}/testmoImportJob/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestmoImportJobDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestmoImportJobDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestmoImportJobDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateTestmoImportJob<TArgs extends Prisma.TestmoImportJobAggregateArgs, TQueryFnData = Prisma.GetTestmoImportJobAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTestmoImportJob<TArgs extends Prisma.TestmoImportJobAggregateArgs, TQueryFnData = Prisma.GetTestmoImportJobAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/aggregate`, args, options, fetch);
}

export function useGroupByTestmoImportJob<TArgs extends Prisma.TestmoImportJobGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TestmoImportJobGroupByArgs['orderBy'] } : { orderBy?: Prisma.TestmoImportJobGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TestmoImportJobGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TestmoImportJobGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TestmoImportJobGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TestmoImportJobGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TestmoImportJobGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTestmoImportJob<TArgs extends Prisma.TestmoImportJobGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TestmoImportJobGroupByArgs['orderBy'] } : { orderBy?: Prisma.TestmoImportJobGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TestmoImportJobGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TestmoImportJobGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TestmoImportJobGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TestmoImportJobGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TestmoImportJobGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/groupBy`, args, options, fetch);
}

export function useCountTestmoImportJob<TArgs extends Prisma.TestmoImportJobCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TestmoImportJobCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/count`, args, options, fetch);
}

export function useSuspenseCountTestmoImportJob<TArgs extends Prisma.TestmoImportJobCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TestmoImportJobCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestmoImportJobCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/count`, args, options, fetch);
}
import type { TestmoImportStatus, TestmoImportPhase } from '@prisma/client';

export function useCheckTestmoImportJob<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; createdById?: string; status?: TestmoImportStatus; statusMessage?: string; phase?: TestmoImportPhase; storageKey?: string; storageBucket?: string; originalFileName?: string; originalFileSize?: number; totalDatasets?: number; processedDatasets?: number; totalRows?: number; processedRows?: number; durationMs?: number; cancelRequested?: boolean; error?: string; processedCount?: number; errorCount?: number; skippedCount?: number; totalCount?: number; currentEntity?: string; estimatedTimeRemaining?: string; processingRate?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('TestmoImportJob', `${endpoint}/testmoImportJob/check`, args, options, fetch);
}
